In [2]:
import numpy as np
import pandas as pd

In [46]:
#filePath = '../data/Age50_DataExtract.csv'
filePath = '../data/mod2.csv'

In [47]:
df = pd.read_csv(filePath)

In [48]:
df

fyAGE  CCCfy49  CCCfy53  CCCfy98  CCCfy98.1  CCCfy100  CCCfy101  CCCfy128  \
0     50        0        0        0          0         0         0         0   
1     50        0        0        0          0         0         0         0   
2     50        0        0        0          0         0         0         0   
3     50        0        0        0          0         0         0         0   
4     50        0        0        0          0         0         0         1   
5     50        0        0        1          0         0         0         0   
6     50        1        1        0          1         0         0         0   
7     50        0        0        0          0         0         0         0   
8     50        0        0        1          0         0         0         0   

   CCCfy204  CCCfy205  ...   CCCsy49  CCCsy53  CCCsy98  CCCsy100  CCCsy101  \
0         1         0  ...         0        0        0         0         0   
1         0         0  ...         0        0        0         0         0   
2         0         0  ...         0        0        0         0         0   
3         0         0  ...         0        0        0         0         0   
4         0         0  ...         0        0        0         0         0   
5         0         0  ...         0        0        0         0         0   
6         0         0  ...         1        1        1         0         0   
7         0         0  ...         0        0        0         0         0   
8         0         0  ...         0        0        0         0         0   

   CCCsy128  CCCsy204  CCCsy205  CCCsy651  Cats  
0         0         0         0         0     0  
1         0         0         0         0     2  
2         0         0         0         0     3  
3         0         0         0         0     4  
4         0         0         0         0     5  
5         0         0         0         0     6  
6         0         1         0         0     7  
7         0         0         0         0     8  
8         0         0         0         0     9  

[9 rows x 21 columns]

In [49]:
tups = [tuple(x) for x in df.values]
data_arr = np.asarray(tups)

In [50]:
data_arr
data_arr.shape

(9, 21)

In [53]:
d1 = pd.get_dummies(df)
d1 

fyAGE  CCCfy49  CCCfy53  CCCfy98  CCCfy98.1  CCCfy100  CCCfy101  CCCfy128  \
0     50        0        0        0          0         0         0         0   
1     50        0        0        0          0         0         0         0   
2     50        0        0        0          0         0         0         0   
3     50        0        0        0          0         0         0         0   
4     50        0        0        0          0         0         0         1   
5     50        0        0        1          0         0         0         0   
6     50        1        1        0          1         0         0         0   
7     50        0        0        0          0         0         0         0   
8     50        0        0        1          0         0         0         0   

   CCCfy204  CCCfy205  ...   CCCsy49  CCCsy53  CCCsy98  CCCsy100  CCCsy101  \
0         1         0  ...         0        0        0         0         0   
1         0         0  ...         0        0        0         0         0   
2         0         0  ...         0        0        0         0         0   
3         0         0  ...         0        0        0         0         0   
4         0         0  ...         0        0        0         0         0   
5         0         0  ...         0        0        0         0         0   
6         0         0  ...         1        1        1         0         0   
7         0         0  ...         0        0        0         0         0   
8         0         0  ...         0        0        0         0         0   

   CCCsy128  CCCsy204  CCCsy205  CCCsy651  Cats  
0         0         0         0         0     0  
1         0         0         0         0     2  
2         0         0         0         0     3  
3         0         0         0         0     4  
4         0         0         0         0     5  
5         0         0         0         0     6  
6         0         1         0         0     7  
7         0         0         0         0     8  
8         0         0         0         0     9  

[9 rows x 21 columns]

In [55]:
df = pd.DataFrame([
            ['green', 1, 10.1, 0], 
            ['red', 2, 13.5, 1], 
            ['blue', 3, 15.3, 0]])

df.columns = ['color', 'size', 'prize', 'class label']
df

color  size  prize  class label
0  green     1   10.1            0
1    red     2   13.5            1
2   blue     3   15.3            0

In [59]:
pd.get_dummies(df)

size  prize  class label  color_blue  color_green  color_red
0     1   10.1            0           0            1          0
1     2   13.5            1           0            0          1
2     3   15.3            0           1            0          0

In [61]:
data_arr

array([[50,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  3],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  4],
       [50,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  5],
       [50,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  6],
       [50,  1,  1,  0,  1,  0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,
         0,  1,  0,  0,  7],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  8],
       [50,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  9]])

In [62]:
data_arr.shape

(9, 21)

In [66]:
# Make multi valued discrete data into binary


# converts column j to binary vec
def convert_discrete_data(data, j):
    # set of values
    valset = set(data[:,j])
    valdict = {}
    count = 0
    for i in valset:
        valdict[i] = count
        count += 1
    
    m = len(valset)
    
    # Now remap the data set
    
    N = data.shape[0]
    
    ndata = np.zeros((N,m))
    
    for i in range(N):
        pos = valdict[data[i,j]]
        ndata[i,pos] = 1 #one hot encoding
    
    new_arr = np.concatenate((data[:,:j], ndata, data[:,j+1:]), axis=1)
    return new_arr
                            


nd = convert_discrete_data(data_arr,20)









In [71]:
data_arr[:5]

array([[50,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  3],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  4],
       [50,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  5]])

In [69]:
nd[:5]

array([[50.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [50.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [50.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [50.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.],
       [50.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.]])

In [70]:
data_arr[:5]

array([[50,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  3],
       [50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  4],
       [50,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  5]])